export const Theme = {
  colors: {
    primary: "#753D3D",
    secondary: "#FFF0E5",
    background: "#FFFFFF",
    secondaryBackground: "#FFF0E5",
    text: "#000000",
    textSecondary: "#FFFFFF",
    inputBackground: "#F1F1F1",
    inputDefaultText: "#646464",
    disabledButton: "#D9D9D9",
    accentGray: "#2c2828ff",
  },
  sizes: {
    tinyText: 14,
    smallText: 18,
    mediumText: 20,
    largeText: 24,
    headerTitle: 28,
    tinyIcon: 8,
    smallIcon: 16,
    mediumIcon: 22,
    largeIcon: 26,
  },
};
